name: Connventional Changelog Generator
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - 'CHANGELOG.md'

jobs:
  build:
    name: Connventional Changelog Generator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SERVICE_TOKEN }}
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.SERVICE_TOKEN }}
          git-user-email: ckilpatrick20@gmail.com
          git-user-name: ckilpatricktest
          skip-version-file: true
