name: Connventional Changelog Generator
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'

jobs:
  build:
    name: Connventional Changelog Generator
    runs-on: ubuntu-latest
    steps:
      - name: Temporarily disable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        if: always()
        with:
           access-token: ${{ secrets.ACCESS_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-version-file: true
      - name: Enable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        if: always()  # Force to always run this step to ensure "include administrators" is always turned back on
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
